development: &default
  adapter: postgresql
  database: sc2-box
  username: ocowchun
  port: 5432
  host: localhost
  pool: 10

production: *default

test:
  host: localhost
  adapter: postgresql
  database: sc2-box-test
  username: ocowchun
  port: 5432
  pool: 10
  min_messages: warning